
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel-rest
  template:
    metadata:
      labels:
        app: hotel-rest
    spec:
      containers:
      - name: hotel-rest
        image: hotel-rest:local
        ports:
        - containerPort: 8080
